---
#Copy war files from Jenkins server to Tomcat server
- name: Grant user permission read and write to war file
  file:
    path: /var/lib/jenkins/workspace/Ansible-Tomcat-deploy/target
    state: directory
    mode: u=rwX,g=rX,o=rX
    recurse: true

- name: Copy war file
  copy: 
    src: /var/lib/jenkins/workspace/Ansible-Tomcat-deploy/target/SampleWebApplication.war
    dest: /opt/tomcat/webapps/
    force: yes

- name: Copy site message 
  copy: 
    src:  /var/lib/jenkins/workspace/Ansible-Tomcat-deploy/target/SampleWebApplication
    dest: /opt/tomcat/webapps 
    force: yes

  notify: 
  - restart tomcat
